import apiService from './api';
import type {
  Run,
  RunWithMetadata,
  Artifact,
  RunResults,
  PaginatedResponse,
  RunStatus,
  RunTimelineEntry
} from '@/types';

export const runsService = {
  /**
   * List all runs for a project with optional filtering and pagination.
   */
  async getRuns(
    projectId: string,
    filters?: { status?: RunStatus; page?: number; pageSize?: number }
  ): Promise<PaginatedResponse<RunWithMetadata>> {
    const { status, page = 1, pageSize = 20 } = filters || {};
    const params: Record<string, unknown> = { page, pageSize };
    if (status) {
      params.status = status;
    }

    const response = await apiService.get<RunWithMetadata[]>(
      `/projects/${projectId}/runs`,
      params
    );

    // Note: The backend currently returns a simple list for mocks.
    // In a production API, the response would already be a PaginatedResponse.
    return {
      data: response.data,
      total: response.data.length,
      page,
      pageSize,
      totalPages: Math.ceil(response.data.length / pageSize),
    };
  },

  /**
   * Get detailed information for a specific run.
   */
  async getRun(runId: string): Promise<RunWithMetadata> {
    const response = await apiService.get<RunWithMetadata>(`/runs/${runId}`);
    return response.data;
  },

  /**
   * Retrieve the results of a completed run.
   */
  async getRunResults(runId: string): Promise<RunResults> {
    const response = await apiService.get<RunResults>(`/runs/${runId}/results`);
    return response.data;
  },

  /**
   * List all artifacts generated by a run.
   */
  async getRunArtifacts(runId: string): Promise<Artifact[]> {
    const response = await apiService.get<Artifact[]>(`/runs/${runId}/artifacts`);
    return response.data;
  },

  /**
   * Download a specific artifact by its ID.
   */
  async downloadArtifact(artifactId: string): Promise<Blob> {
    const response = await apiService.get<any>(`/artifacts/${artifactId}/download`);
    // Return as a Blob for the frontend to handle as a file download
    return new Blob([JSON.stringify(response.data)], { type: 'application/json' });
  },

  /**
   * Trigger a new run for a given specification.
   */
  async triggerRun(
    projectId: string,
    specId: string,
    options?: {
      providerId?: string;
      modelIdentifier?: string;
    }
  ): Promise<Run> {
    const response = await apiService.post<Run>('/runs', {
      projectId,
      specId,
      triggeredBy: 'web',
      ...options,
    });
    return response.data;
  },

  /**
   * Cancel a run that is currently queued or running.
   */
  async cancelRun(runId: string): Promise<void> {
    await apiService.post<void>(`/runs/${runId}/cancel`);
  },

  /**
   * Get the execution timeline of a run to track its progress.
   */
  async getRunTimeline(runId: string): Promise<RunTimelineEntry[]> {
    const response = await apiService.get<RunTimelineEntry[]>(`/runs/${runId}/timeline`);
    return response.data;
  },
};
